# -*- coding: utf-8 -*-
"""KNN_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cCtB4UPISK-3pLFpNOTYSBtwLb68FGG
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Step 1: Load the dataset
uploaded_file_path = '/content/heart.csv'

data = pd.read_csv(uploaded_file_path)
print("/content/heart.csv")

print("First few rows of the dataset:")
print(data.head())

# Step 4: Features (X) and target (y)
X = data.drop(columns=["target"])  # Independent variables
y = data["target"]  # Dependent variable

# Step 4: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Step 5: Train the KNN model
knn = KNeighborsClassifier(n_neighbors=5)  # You can change the number of neighbors (k)
knn.fit(X_train, y_train)

# Step 6: Evaluate the model
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))