# -*- coding: utf-8 -*-
"""RandomForestTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8m4KCzj92FOYUtSomm97wLWfWWFQdDk
"""

# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

# Load the dataset
file_path = '/content/heart.csv'  # Update path if the file is elsewhere
data = pd.read_csv(file_path)
# Preview the dataset
print("Dataset Preview:")
print(data.head())

X=data.drop("target",axis=1)
y=data["target"]

# Split dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest model
rf_model = RandomForestClassifier(random_state=42)
# Train the model
rf_model.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))